### ISSUE TITLE
Arith: treat "x" value in operator's limit as 0

### ISSUE THREAD

**Issue by frncesc** [projectestac/jclic.js#10]
The LIM_CH array of strings defined in [edu.xtec.jclic.automation.arith.Operator.java](https://github.com/projectestac/jclic/blob/master/src/core/edu/xtec/jclic/automation/arith/Operator.java#L48) makes use of "x" to indicate "0". This strange behavior was probably inherited from Clic 3.0 for Windows, to distinguish between "undefined" and "0".

JClic.js should take in account this special case as an exception when parsing ".jclic" files.

This issue was [originally reported](https://github.com/projectestac/jclic/issues/20) by @belekes in the JClic repository.

**Comment by frncesc** [comment]
Problem solved in commit 7b0da34
Tested with the sample provided by @belekes, and it works now as expected!
The solution will be published in JClic.js V0.1.38, to be released in two days (expected 02/Nov/2016)

Thanks for reporting!

**Comment by belekes** [comment]
Thanks for solving this problem!
Can we (as users) download a new version of JClic Author, so we can solve the problems in our exercises?
Thanks!
Peter

**Comment by frncesc** [comment]
Well... this problem was not related to JClic Author, but to JClic.js (the JavaScript player used in HTML5 export). Your exercise was OK, but JClic.js misunderstood it.
The error is now solved, and the new version of JClic.js replaced the buggy one in https://clic.xtec.cat/dist/jclic.js/jclic.min.js (and in other download sites) so everyone is watching now the activities as they really are.

Anyway, the latest version of JClic Author is always available at:
http://clic.xtec.cat/en/jclic/download.htm
