### ISSUE TITLE
In HTML5 mode, the letters are not centered in the middle of the cell

### ISSUE THREAD

**Issue by DavisMamularu** [projectestac/jclic.js#22]
I developed a game in JCLIC WORD SEARCH that has a display problem in HTML5 mode. The letters are not centered in the middle of the cell as they appear in JCLIC PLAYER. I can modify something in the generated files to correct this problem. Thanks

**Comment by frncesc** [comment]
Thanks for reporting!

Yes, you are right. Text was not well centered on grid cells and boxes.

I have changed the algorithm for calculating the vertical displacement of text elements, and it's now solved in version 1.1.21

Please check if it's now OK also in your activities.

**Comment by DavisMamularu** [comment]
Thanks for fixing the algorithm. It's perfect for my little game.
