### ISSUE TITLE
URL changing when choosing other site language

### ISSUE THREAD

**Issue by ruiefe** [projectestac/jclic.js#7]
I tried this in Chrome, Firefox - Windows - and Safari - IOS,
- When I choose portuguese activities, and then I change the site language to catalán, everithing works. When I choose Spanish, the occitan activities show (the URL changes to http://clic.xtec.cat/repo/index.html?language=oc)
- I tried choosing the english activities and everithing seemed ok. When I changed the site language to Spanish and then went to english language again, I had the Greek activities showing. After changing the site language again, I had one Spanish and Araucanian activity showing.

**Comment by frncesc** [comment]
This issue seems to be related to project [jclic-repo](https://github.com/projectestac/jclic-repo).

Moved to: https://github.com/projectestac/jclic-repo/issues/1

Thanks for reporting!
