### ISSUE TITLE
Fill in Blanks - Content not overwriting the blue line

### ISSUE THREAD

**Issue by ruiefe** [projectestac/jclic.js#8]
When filling blanks, the blue line (provided as a cue to the user to know where to write) pushes the everything to the right, causing confusion to the user (e.g. Actividad de llenar huecos con imagenes where the blue lines will not stay in place)

**Comment by frncesc** [comment]
I think this was already solved in commits 180c684 and 887a2d1.

The error was produced by commit ba5330d, when function `processEvent` was removed from `TextActivityBase`. This broke `processEvent` in `FillInBlanks` and also in other classes derived from `TextActivityBase`.

Please check if it works well, and reopen the bug if needed.

Thnx!
